### ISSUE TITLE
Running code by using Anaconda problem

### ISSUE THREAD

**Issue by cglynnhr** [aprsa/dips#5]
Hi everyone,

I'm trying to use dips with anaconda (and winpython) and facing a problem:

"dips is not recognized..." 

I have already added paths but no cheers. I'm wondering that anyone has the same issue because I don't know that this is my bad or arises from the code. By the way, all is well in linux.

Anaconda 3.7 and windows 10.

Any help is appreciated.
Best, Caglayan

**Comment by horvatm** [comment]
At what stage does this error occur? Is this while installing via
```
python3 setup.py install
```
or while running in an working directory. How do you trying to run this program on windows? Doing
```
python3 <path>/bin/dips
```
or just writing
```
dips
```
in cmd ?

**Comment by horvatm** [comment]
Additional information about running python on Windows OS 10:

a. If you want to run python scripts without specifying extension then extend PATHEXT environment variable with default python extension .py by writing
```
SET  PATHEXT=%PATHEXT%;.py
```
in command prompt (cmd) or add .py to PATHEXT in system environment in "system properties"

b. Additionally, you need to  associate .py with python3 application. This is done by finding one python script (something.py) and then do
```
Right mouse click > Open with > Choose another app > search for python of your choice
```

**Comment by cglynnhr** [comment]
Hi martin,

Sorry for the late reply. Installing is ok with both way (pip or setup.py). Python has already added path also dips too. I'm using other codes in cmd without any problem. I.e. for `python dips kic3953981_sap.data -b 101...` error is 

"Traceback (most recent call last):
  File "dips", line 45, in <module>
    dips = Dips(vars(cmdargs))
  File "<path>\lib\site-packages\dips\dips.py", line 51, in __init__
    self.data = np.loadtxt(args['finput'], usecols=args['cols'])
  File "<path>\lib\site-packages\numpy\lib\npyio.py", line 898, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: 'kic3953981_sap.data'" 

but there is in the same directory. Also I tried some combinations for directory but nothing.

When I use `dips kic3953981_sap.data -b 101...`: 
'dips' is not recognized as an internal or external command, operable program or batch file.

I have already tried `SET  PATHEXT=%PATHEXT%` but nothing changed.

It seems I'm missing something or doing a silly mistake. By the way it's not a big deal for me for now if you don't have time for this issue. As I said before dips is working well in linux. I have already used dips in linux so no problem. Just it would be more practical that using dips in windows. 

Thank you.
